Dockerfile
Fixes #4 by:
1. run as USER leinuser
2. verifying download signatures
And, use `lein-pkg` instead of `lein` script as it should.
=> verify signatures and run as USER leinuser

Dockerfile
Update Leiningen with v2.5.2 (refs #14)
But strange gpg output:
```
Comparing archive checksum ...
2.5.2.tar.gz: OK
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 05696D78 from hkp server pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 05696D78: public key "Jean Niklas L'orange (hyPiRion) <jeannikl@hypirion.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Verifying Jar file signature ...
gpg: assuming signed data in …
```
=> Bump lein to 2.5.2

Dockerfile, README.md
We would love to use this docker image to build ClojureScript applications, but it is useless without a readline wrapper for Figwheel's browser REPL. Is this change a possibility?
=> Add rlfe for REPL usage

alpine/Dockerfile
This is a less-is-more build, so users who need rlwrap (or similar) can
either install it themselves or stick with the Ubuntu-based image.
As requested in the [docker-library pull request](https://github.com/docker-library/official-images/pull/1587#issuecomment-205453648).
=> Stop installing rlwrap in alpine build

alpine/Dockerfile
Includes Alpine 3.4 & security fixes in Java.
=> Update to java:8u92-alpine upstream image

Dockerfile, alpine/Dockerfile, install-boot.sh, install-lein.sh
Opening this for discussion about the approach. This would close #19.
I added build args (w/ defaults for current behavior) that allow building images with any version of either boot or leiningen.
I'm thinking we could publish more image tags along the lines of:
- `docker build -t clojure:lein-2.7.1 .` same as now
- `docker build -t clojure:lein-2.7.1-alpine alpine` same as now
- `docker build -t clojure:boot-2.7.1 --build-arg BUILD_TOOL=boot --build-arg TOOL_VERSION=2.7.1 .` will build a boot-based image; note that boot and lein's latest versions happen to be in sync right now but presumably that won't always be the case
- `docker build -t clojure:boot-2.7.1-alpine --build-arg BUILD_TOOL=boot --build-arg TOOL_VERSION=2.7.1 alpine` will build an alpine-based image w/ boot instead of lein …
=> Add boot variants

.dockerignore, README.md, hooks/build, hooks/post_push
This contains updates and edits to the README for Alpine-based images, the new leiningen vs. boot images, and other misc. fixes and cleanups.
It also appears that in order to use build args in automated Docker Hub builds, we need to use a build hook. The post_push hook was added to push `clojure:lein`, `clojure:lein-alpine`, `clojure:boot`, and `clojure:boot-alpine` tags as well.
=> Hooks and readme updates

Dockerfile-lein.template, alpine/lein/Dockerfile, debian/lein/Dockerfile
The boot images come with a few jars pre-installed, clojure 1.8.0 among them, due to the way boot works. Installing the latest stable release clojure jar seems like a good thing to do for the lein images too. After this change, you can run the lein images w/ `lein repl` as the command and the REPL will come up without having to download anything. And it saves every downstream build from needing to re-install the basic language jars every time (assuming they're on version 1.8.0).
Curious what you think about this, @Quantisan.
=> Add clojure 1.8.0 jar in lein images

Dockerfile-lein.template, alpine/lein/Dockerfile, debian/lein/Dockerfile
I also removed the blank lines from the big `RUN` in the Dockerfiles because the latest version of Docker is warning that those will soon generate a build error.
=> Update leiningen to 2.8.0

.gitignore, src/docker_clojure/core.clj, src/docker_clojure/dockerfile.clj
Some of the recently-merged changes broke our compatibility with the upstream build system. They want a `Directory` that contains both a `Dockerfile` and the build root (which can just be empty for our needs).
So I've refactored things to work that way again with the new Clojure build system.
=> Build in dirs for compatibility w/ official images

src/docker_clojure/dockerfile/tools_deps.clj, target/openjdk-14-alpine/tools-deps/Dockerfile
Fixes #77
Sorry for the delay getting this together.
=> Leave bash installed in alpine image

src/docker_clojure/core.clj, src/docker_clojure/dockerfile.clj, src/docker_clojure/dockerfile/boot.clj, src/docker_clojure/dockerfile/lein.clj, src/docker_clojure/dockerfile/tools_deps.clj, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-11-stretch/latest/Dockerfile, target/openjdk-11-stretch/lein/Dockerfile, target/openjdk-13-buster/lein/Dockerfile, target/openjdk-13-slim-buster/lein/Dockerfile, target/openjdk-14-alpine/lein/Dockerfile, target/openjdk-14-buster/lein/Dockerfile, target/openjdk-14-slim-buster/lein/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile, target/openjdk-8-stretch/lein/Dockerfile
An idea coming out of discussion on #80. Implementing this consisted mostly of splitting up the install commands from the runtime commands (literally the `CMD` lines) in the generated Dockerfiles.
I also removed the lein GPG verification because it is just horrendously unreliable, and I have had no success improving it. With the number of image variants we're building nowadays, I can't get them to all successfully build because one or more will inevitably fail at this step. So unfortunately I think we need to drop it.
=> Install all build tools in latest tag

src/docker_clojure/core.clj, src/docker_clojure/dockerfile/lein.clj, target/openjdk-11-buster/boot/Dockerfile, target/openjdk-11-buster/lein/Dockerfile, target/openjdk-11-buster/tools-deps/Dockerfile, target/openjdk-11-slim-buster/latest/Dockerfile, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-14-buster/lein/Dockerfile, target/openjdk-14-slim-buster/lein/Dockerfile, target/openjdk-15-alpine/boot/Dockerfile, target/openjdk-15-alpine/lein/Dockerfile, target/openjdk-15-alpine/tools-deps/Dockerfile, target/openjdk-15-buster/boot/Dockerfile, target/openjdk-15-buster/lein/Dockerfile, target/openjdk-15-buster/tools-deps/Dockerfile, target/openjdk-15-slim-buster/boot/Dockerfile, target/openjdk-15-slim-buster/lein/Dockerfile, target/openjdk-15-slim-buster/tools-deps/Dockerfile, target/openjdk-8-buster/boot/Dockerfile, target/openjdk-8-buster/lein/Dockerfile, target/openjdk-8-buster/tools-deps/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile, test/docker_clojure/core_test.clj
This builds on top of #84 (just because I'm lazy) so feel free to review that first. Just updates leiningen to the recently released 2.9.3 version. The relevant commit for this PR is f1c6fc1.
=> Update leiningen to 2.9.3

src/docker_clojure/dockerfile/lein.clj, target/openjdk-11-buster/lein/Dockerfile, target/openjdk-11-slim-buster/latest/Dockerfile, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-14-buster/lein/Dockerfile, target/openjdk-14-slim-buster/lein/Dockerfile, target/openjdk-15-alpine/lein/Dockerfile, target/openjdk-15-buster/lein/Dockerfile, target/openjdk-15-slim-buster/lein/Dockerfile, target/openjdk-8-buster/lein/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile
Now that technomancy has uploaded his key to keys.openpgp.org (thanks again!), use that to more reliably retrieve the key and verify the leiningen download.
=> Feature: restore PGP sig verification for leiningen

README.md, src/docker_clojure/core.clj, target/openjdk-16-alpine/boot/Dockerfile, target/openjdk-16-alpine/lein/Dockerfile, target/openjdk-16-alpine/tools-deps/Dockerfile, target/openjdk-16-buster/boot/Dockerfile, target/openjdk-16-buster/lein/Dockerfile, target/openjdk-16-buster/tools-deps/Dockerfile, target/openjdk-16-slim-buster/boot/Dockerfile, target/openjdk-16-slim-buster/lein/Dockerfile, target/openjdk-16-slim-buster/tools-deps/Dockerfile
New JDK version added. I also gave the README a refresh pass. I also snuck in a small enhancement that pulls upstream images before building on them. I noticed that sometimes builds would be different on my local machine if I had an outdated upstream `openjdk` image already cached. This helps ensure (but does not guarantee) that my local builds are the same as what will get built on the Docker image infrastructure.
After this I'm going to work on reverting our tools-deps images to stable releases only, which I recently learned were a thing: https://groups.google.com/u/2/g/clojure/c/cS8KjpTKBl0
=> Add openjdk 16

.github/workflows/main.yml, build-images.sh, src/docker_clojure/core.clj, src/docker_clojure/dockerfile/tools_deps.clj, target/openjdk-11-buster/tools-deps/Dockerfile, target/openjdk-11-slim-buster/latest/Dockerfile, target/openjdk-11-slim-buster/tools-deps/Dockerfile, target/openjdk-14-buster/tools-deps/Dockerfile, target/openjdk-14-slim-buster/tools-deps/Dockerfile, target/openjdk-15-buster/tools-deps/Dockerfile, target/openjdk-15-slim-buster/tools-deps/Dockerfile, target/openjdk-16-alpine/tools-deps/Dockerfile, target/openjdk-16-buster/tools-deps/Dockerfile, target/openjdk-16-slim-buster/tools-deps/Dockerfile, target/openjdk-8-buster/tools-deps/Dockerfile, target/openjdk-8-slim-buster/tools-deps/Dockerfile, test.sh, update.sh
This is a pretty big release by tools-deps standards and deprecates quite a few CLI calling conventions. Since this project uses tools-deps itself, this PR also updates the `./update.sh`, `./test.sh`, and `./build-images.sh` scripts to use the new conventions.
=> Update: tools-deps to 1.10.1.697

src/docker_clojure/core.clj, src/docker_clojure/dockerfile/lein.clj, target/openjdk-11-buster/lein/Dockerfile, target/openjdk-11-slim-buster/latest/Dockerfile, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-15-buster/lein/Dockerfile, target/openjdk-15-slim-buster/lein/Dockerfile, target/openjdk-16-alpine/lein/Dockerfile, target/openjdk-16-buster/lein/Dockerfile, target/openjdk-16-slim-buster/lein/Dockerfile, target/openjdk-8-buster/lein/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile
Leiningen fixed their packaging script that was making it hard to update to 2.9.4 (hence the version skip) and released 2.9.5. I'll merge this shortly. There is a tools-deps update coming hot on its heels too.
=> Update: lein 2.9.5

src/docker_clojure/core.clj, target/openjdk-17-alpine/boot/Dockerfile, target/openjdk-17-alpine/lein/Dockerfile, target/openjdk-17-alpine/tools-deps/Dockerfile, target/openjdk-17-buster/boot/Dockerfile, target/openjdk-17-buster/lein/Dockerfile, target/openjdk-17-buster/tools-deps/Dockerfile, target/openjdk-17-slim-buster/boot/Dockerfile, target/openjdk-17-slim-buster/lein/Dockerfile, target/openjdk-17-slim-buster/tools-deps/Dockerfile
...and stop building openjdk-16-alpine variants as upstream no longer supports it (as usual for non-EA alpine builds).
=> Add openjdk-17 variants

README.md, src/docker_clojure/core.clj, src/docker_clojure/dockerfile/tools_deps.clj, target/openjdk-11-buster/tools-deps/Dockerfile, target/openjdk-11-slim-buster/latest/Dockerfile, target/openjdk-11-slim-buster/tools-deps/Dockerfile, target/openjdk-16-buster/tools-deps/Dockerfile, target/openjdk-16-slim-buster/tools-deps/Dockerfile, target/openjdk-17-alpine/tools-deps/Dockerfile, target/openjdk-17-buster/tools-deps/Dockerfile, target/openjdk-17-slim-buster/tools-deps/Dockerfile, target/openjdk-8-buster/tools-deps/Dockerfile, target/openjdk-8-slim-buster/tools-deps/Dockerfile
Mostly a typical tools-deps version bump, except for what's in f5a80ec. See commit message for details.
Might need to add something to the README about enabling buildx to support that `--platform` flag.
=> Update tools-deps to 1.10.3.833 & apply a band-aid fix for building on M1 Macs

src/docker_clojure/core.clj, src/docker_clojure/dockerfile.clj, src/docker_clojure/dockerfile/boot.clj, src/docker_clojure/dockerfile/lein.clj, src/docker_clojure/dockerfile/tools_deps.clj, target/openjdk-11-bullseye/lein/Dockerfile, target/openjdk-11-buster/lein/Dockerfile, target/openjdk-11-slim-bullseye/latest/Dockerfile, target/openjdk-11-slim-bullseye/lein/Dockerfile, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-16-bullseye/lein/Dockerfile, target/openjdk-16-buster/lein/Dockerfile, target/openjdk-16-slim-bullseye/lein/Dockerfile, target/openjdk-16-slim-buster/lein/Dockerfile, target/openjdk-17-bullseye/lein/Dockerfile, target/openjdk-17-buster/lein/Dockerfile, target/openjdk-17-slim-bullseye/lein/Dockerfile, target/openjdk-17-slim-buster/lein/Dockerfile, target/openjdk-18-alpine/lein/Dockerfile, target/openjdk-18-bullseye/lein/Dockerfile, target/openjdk-18-buster/lein/Dockerfile, target/openjdk-18-slim-bullseye/lein/Dockerfile, target/openjdk-18-slim-buster/lein/Dockerfile, target/openjdk-8-bullseye/lein/Dockerfile, target/openjdk-8-buster/lein/Dockerfile, target/openjdk-8-slim-bullseye/lein/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile, test/docker_clojure/dockerfile_test.clj
While trying to address #132 I noticed that leiningen 2.9.6- versions weren't building because of the author's recent public key change. Fixing that led me to implement a couple things I've been meaning to improve anyway. 2.9.7 is out, but I want to get this and #126 in first before releasing that.
=> Fix older lein builds

.gitignore, README.md, src/docker_clojure/core.clj, target/openjdk-11-bullseye/tools-deps/Dockerfile, target/openjdk-11-buster/tools-deps/Dockerfile, target/openjdk-11-slim-bullseye/latest/Dockerfile, target/openjdk-11-slim-bullseye/tools-deps/Dockerfile, target/openjdk-11-slim-buster/tools-deps/Dockerfile, target/openjdk-17-bullseye/tools-deps/Dockerfile, target/openjdk-17-buster/tools-deps/Dockerfile, target/openjdk-17-slim-bullseye/tools-deps/Dockerfile, target/openjdk-17-slim-buster/tools-deps/Dockerfile, target/openjdk-18-alpine/tools-deps/Dockerfile, target/openjdk-18-bullseye/tools-deps/Dockerfile, target/openjdk-18-buster/tools-deps/Dockerfile, target/openjdk-18-slim-bullseye/tools-deps/Dockerfile, target/openjdk-18-slim-buster/tools-deps/Dockerfile, target/openjdk-8-bullseye/tools-deps/Dockerfile, target/openjdk-8-buster/tools-deps/Dockerfile, target/openjdk-8-slim-bullseye/tools-deps/Dockerfile, target/openjdk-8-slim-buster/tools-deps/Dockerfile
Mostly a standard version bump but also took the opportunity to have the builder code build all working platforms (which is _really_ slow)
=> Update tools-deps to 1.10.3.1020 & build all working platforms

README.md, src/docker_clojure/core.clj, target/eclipse-temurin-17-jdk-alpine/boot/Dockerfile, target/eclipse-temurin-17-jdk-alpine/boot/entrypoint, target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-17-jdk-alpine/lein/entrypoint, target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile, target/eclipse-temurin-17-jdk-alpine/tools-deps/entrypoint, target/eclipse-temurin-17-jdk-alpine/tools-deps/rlwrap.retry, target/eclipse-temurin-18-jdk-alpine/boot/Dockerfile, target/eclipse-temurin-18-jdk-alpine/boot/entrypoint, target/eclipse-temurin-18-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-18-jdk-alpine/lein/entrypoint, target/eclipse-temurin-18-jdk-alpine/tools-deps/Dockerfile, target/eclipse-temurin-18-jdk-alpine/tools-deps/entrypoint, target/eclipse-temurin-18-jdk-alpine/tools-deps/rlwrap.retry
Updates the README and re-enables alpine variants for temurin-based images. Followup to #160
=> Update README & re-enable alpine variants for temurin images

bb.edn, src/docker_clojure/config.clj, src/docker_clojure/core.clj, src/docker_clojure/dockerfile/lein.clj, target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile, target/eclipse-temurin-17-jdk-focal/latest/Dockerfile, target/eclipse-temurin-17-jdk-focal/lein/Dockerfile, target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile, target/eclipse-temurin-18-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-18-jdk-alpine/tools-deps/Dockerfile, target/eclipse-temurin-18-jdk-focal/lein/Dockerfile, target/eclipse-temurin-18-jdk-focal/tools-deps/Dockerfile, target/openjdk-11-bullseye/lein/Dockerfile, target/openjdk-11-bullseye/tools-deps/Dockerfile, target/openjdk-11-buster/lein/Dockerfile, target/openjdk-11-buster/tools-deps/Dockerfile, target/openjdk-11-slim-bullseye/lein/Dockerfile, target/openjdk-11-slim-bullseye/tools-deps/Dockerfile, target/openjdk-11-slim-buster/lein/Dockerfile, target/openjdk-11-slim-buster/tools-deps/Dockerfile, target/openjdk-8-bullseye/lein/Dockerfile, target/openjdk-8-bullseye/tools-deps/Dockerfile, target/openjdk-8-buster/lein/Dockerfile, target/openjdk-8-buster/tools-deps/Dockerfile, target/openjdk-8-slim-bullseye/lein/Dockerfile, target/openjdk-8-slim-bullseye/tools-deps/Dockerfile, target/openjdk-8-slim-buster/lein/Dockerfile, target/openjdk-8-slim-buster/tools-deps/Dockerfile
I added the variant filtering so when I'm doing PRs like this I can run e.g. this:
`bb run build-images :build-tool tools-deps` and only build those images rather than waiting on / visually filtering out the lein and boot variants.
=> Update tools-deps variants & add a feature for filtering variants in CLI commands

src/docker_clojure/manifest.clj, src/docker_clojure/util.clj
The new manifest generation code was inadvertently not generating the `tools-deps`, `lein`, and `boot` tags which we used to have in the manually-maintained manifest and are handy for one-off commands and what not. This restores those to the programmatically-generated manifest.
=> Fix build-tool-only tags

bb.edn, src/docker_clojure/manifest.clj, test/docker_clojure/manifest_test.clj
Noticed there were still some missing tag variants in the manifest, so I wrote some tests for the missing ones and then got them to pass. Need to add more tests for the working ones for regression-catching. But that's for later.
=> Fix missing tags

src/docker_clojure/config.clj
This variant isn't building due to something that changed in a recent JDK 8 version bump. I don't think it's worth the time to find a workaround given how niche this variant is.
=> Exclude boot JDK 8 Alpine variant

src/docker_clojure/config.clj, src/docker_clojure/dockerfile/lein.clj, target/debian-bookworm-11/lein/Dockerfile, target/debian-bookworm-17/lein/Dockerfile, target/debian-bookworm-21/latest/Dockerfile, target/debian-bookworm-21/lein/Dockerfile, target/debian-bookworm-8/lein/Dockerfile, target/debian-bookworm-slim-11/lein/Dockerfile, target/debian-bookworm-slim-17/lein/Dockerfile, target/debian-bookworm-slim-21/lein/Dockerfile, target/debian-bookworm-slim-8/lein/Dockerfile, target/debian-bullseye-11/lein/Dockerfile, target/debian-bullseye-17/lein/Dockerfile, target/debian-bullseye-21/lein/Dockerfile, target/debian-bullseye-8/lein/Dockerfile, target/debian-bullseye-slim-11/lein/Dockerfile, target/debian-bullseye-slim-17/lein/Dockerfile, target/debian-bullseye-slim-21/lein/Dockerfile, target/debian-bullseye-slim-8/lein/Dockerfile, target/eclipse-temurin-11-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-11-jdk-focal/lein/Dockerfile, target/eclipse-temurin-11-jdk-jammy/lein/Dockerfile, target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-17-jdk-focal/lein/Dockerfile, target/eclipse-temurin-17-jdk-jammy/lein/Dockerfile, target/eclipse-temurin-21-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-21-jdk-jammy/lein/Dockerfile, target/eclipse-temurin-8-jdk-alpine/lein/Dockerfile, target/eclipse-temurin-8-jdk-focal/lein/Dockerfile, target/eclipse-temurin-8-jdk-jammy/lein/Dockerfile
Slightly more than a typical upstream version bump due to Leiningen using a new GPG key from this version forward (presumably).
I'll go ahead and merge to get the version bump out there, but let me know if you'd like to see anything changed @Quantisan.
=> Update leiningen to 2.11.0

README.md
Based on [this Slack conversation](https://clojurians.slack.com/archives/C03S1KBA2/p1732194932147949), it was determined that not everyone understood what it meant to be a "Docker Official Image." This change to the top of the README is intended to clarify that.
Anyone reading this, let me know if you have additional suggestions.
=> Clarify Docker Official Image meaning & status

README.md
And I fixed a small inconsistency in how we were representing image tag formats between tools-deps and lein.
=> Update README for new Alpine arm64 images
