Dockerfile

Update to Java 8

---

README.md
onbuild/Dockerfile

This image makes building derivative images easier.

Add clojure:onbuild image for building derivative images easier

---

Dockerfile

lein 2.5.3

---

alpine/Dockerfile

Image size is ~175MB instead of ~660MB.

Add alpine-based build

---

alpine-onbuild/Dockerfile

Seemed like we should have this too. :)

Add alpine-onbuild Dockerfile

---

Dockerfile
alpine/Dockerfile

...and switch to "openjdk" upstream Docker image since they are deprecating the "java" image in favor of it.

Update to lein 2.7.0

---

alpine/boot/Dockerfile
debian/boot/Dockerfile
variants.sh

Update boot to 2.8.1

---

src/docker_clojure/core.clj
target/openjdk-11/debian/tools-deps/Dockerfile
target/openjdk-8/alpine/tools-deps/Dockerfile
target/openjdk-8/debian/tools-deps/Dockerfile

Update tools-deps to 1.10.0.442

---

src/docker_clojure/core.clj
test/docker_clojure/core_test.clj
test/docker_clojure/dockerfile_test.clj

My bad. Tests don't do much good unless you keep them in sync with the code and run them! I'll see about setting up some GitHub Actions to run them on PRs and merges (CI style).

Fix tests that I failed to update

---

README.md

Noticed the README needed a little love for the recently merged changes.

Update README for latest changes

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-14-buster/tools-deps/Dockerfile
target/openjdk-14-slim-buster/tools-deps/Dockerfile
target/openjdk-15-alpine/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Nothing really interesting to review here. Just creating this PR for the "paper trail." I'll merge it.

Update tools-deps to 1.10.1.590

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-14-buster/tools-deps/Dockerfile
target/openjdk-14-slim-buster/tools-deps/Dockerfile
target/openjdk-15-alpine/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Update tools-deps to 1.10.1.619

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-14-buster/tools-deps/Dockerfile
target/openjdk-14-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-alpine/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

New upstream stable release. Nothing very interesting to review here, so I'll merge it pretty soon.

Update: tools-deps to 1.10.1.708

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-alpine/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

And here is the latest tools-deps update. I'll merge this soon too.

Update: tools-deps 1.10.1.754

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-alpine/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Just another upstream release update. I'll merge shortly.

Update tools-deps 1.10.1.763

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-alpine/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

New upstream release. I'll merge this soon unless there any objections / test failures.

Update: tools-deps to 1.10.2.774

---

deps.edn
src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

New upstream tools-deps release

Update tools-deps to 1.10.2.790

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/lein.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/lein/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/lein/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/lein/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/lein/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/lein/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/lein/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/lein/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/lein/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/lein/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/lein/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/lein/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Another day, another tools-deps release :)

Update tools-deps 1.10.2.796

---

build-images.sh
deps.edn
src/docker_clojure/core.clj
src/docker_clojure/dockerfile/lein.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/lein/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/lein/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/lein/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/lein/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/lein/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/lein/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/lein/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/lein/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/lein/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/lein/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/lein/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

This looked straightforward enough so I went ahead with it.

Update to clojure 1.10.3 and tools deps 1.10.3.814

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/lein/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/lein/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-15-buster/lein/Dockerfile
target/openjdk-15-buster/tools-deps/Dockerfile
target/openjdk-15-slim-buster/lein/Dockerfile
target/openjdk-15-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/lein/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/lein/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/lein/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/lein/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/lein/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/lein/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/lein/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

I'll merge once the CI build is green

Update tools deps to 1.10.3.822

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

I'll merge this when CI passes b/c there's an installer bug in 1.10.3.833.

Update tools-deps to 1.10.3.839

---

clean.sh
src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Found some time to get this pushed up

Update tools-deps to 1.10.3.855

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

I'll merge this when / if the build is green

Update tools-deps to 1.10.3.933

---

src/docker_clojure/core.clj
src/docker_clojure/dockerfile/tools_deps.clj
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-buster/latest/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-16-buster/tools-deps/Dockerfile
target/openjdk-16-slim-buster/tools-deps/Dockerfile
target/openjdk-17-alpine/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

New upstream release
I'll merge when green

Update tools-deps to 1.10.3.943

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/latest/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Fairly standard stuff. I'll merge once build is green.

Update openjdk versions (remove EOL'd 16) and tools-deps (update to 1.10.3.998)

---

src/docker_clojure/dockerfile.clj
target/openjdk-17-slim-bullseye/latest/entrypoint

Feature: clj entrypoint in latest

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Update tools-deps to 1.10.3.1040

---

src/docker_clojure/dockerfile/boot.clj
src/docker_clojure/dockerfile/lein.clj
target/openjdk-11-bullseye/boot/Dockerfile
target/openjdk-11-bullseye/lein/Dockerfile
target/openjdk-11-buster/boot/Dockerfile
target/openjdk-11-buster/lein/Dockerfile
target/openjdk-17-bullseye/boot/Dockerfile
target/openjdk-17-bullseye/lein/Dockerfile
target/openjdk-17-buster/boot/Dockerfile
target/openjdk-17-buster/lein/Dockerfile
target/openjdk-18-bullseye/boot/Dockerfile
target/openjdk-18-bullseye/lein/Dockerfile
target/openjdk-18-buster/boot/Dockerfile
target/openjdk-18-buster/lein/Dockerfile
target/openjdk-8-bullseye/boot/Dockerfile
target/openjdk-8-bullseye/lein/Dockerfile
target/openjdk-8-buster/boot/Dockerfile
target/openjdk-8-buster/lein/Dockerfile

Installs make in non-slim lein and boot variants for those who use it to build their projects
Closes #147

Feature: add make to non slim images

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Standard upstream update; will merge when green

Update tools-deps to 1.10.3.1058

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

standard upstream version bump

Update tools-deps to 1.10.3.1069

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Update tools-deps variants to 1.10.3.1075

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-alpine/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

New upstream release. I'll merge once green.

Update tools-deps to 1.10.3.1087

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-19-alpine/tools-deps/Dockerfile
target/openjdk-19-bullseye/tools-deps/Dockerfile
target/openjdk-19-buster/tools-deps/Dockerfile
target/openjdk-19-slim-bullseye/tools-deps/Dockerfile
target/openjdk-19-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Standard upstream release. Will merge when green.

Update tools-deps variants to 1.11.1.1105

---

src/docker_clojure/core.clj
target/openjdk-11-bullseye/tools-deps/Dockerfile
target/openjdk-11-buster/tools-deps/Dockerfile
target/openjdk-11-slim-bullseye/tools-deps/Dockerfile
target/openjdk-11-slim-buster/tools-deps/Dockerfile
target/openjdk-17-bullseye/tools-deps/Dockerfile
target/openjdk-17-buster/tools-deps/Dockerfile
target/openjdk-17-slim-bullseye/latest/Dockerfile
target/openjdk-17-slim-bullseye/tools-deps/Dockerfile
target/openjdk-17-slim-buster/tools-deps/Dockerfile
target/openjdk-18-bullseye/tools-deps/Dockerfile
target/openjdk-18-buster/tools-deps/Dockerfile
target/openjdk-18-slim-bullseye/tools-deps/Dockerfile
target/openjdk-18-slim-buster/tools-deps/Dockerfile
target/openjdk-19-alpine/tools-deps/Dockerfile
target/openjdk-19-bullseye/tools-deps/Dockerfile
target/openjdk-19-buster/tools-deps/Dockerfile
target/openjdk-19-slim-bullseye/tools-deps/Dockerfile
target/openjdk-19-slim-buster/tools-deps/Dockerfile
target/openjdk-8-bullseye/tools-deps/Dockerfile
target/openjdk-8-buster/tools-deps/Dockerfile
target/openjdk-8-slim-bullseye/tools-deps/Dockerfile
target/openjdk-8-slim-buster/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1113

---

.github/workflows/main.yml
.gitignore
bb.edn
build-images.sh
clean.sh
deps.edn
src/docker_clojure/config.clj
src/docker_clojure/core.clj
src/docker_clojure/manifest.clj
src/docker_clojure/util.clj
test.sh
test/docker_clojure/core_test.clj
test/docker_clojure/dockerfile_test.clj
test/docker_clojure/test_runner.clj
update.sh

Been wanting to do this for a _loooooooooooooonnnnnnnnnnnnnngggggggggg_ time. :)
I also converted the shell scripts to babashka tasks and changed CI to run under bb too.

Feature: generate manifest file

---

src/docker_clojure/config.clj
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-18-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-18-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-18-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Standard version bump. Will merge shortly.

Update tools-deps variants to 1.11.1.1155

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Just a typical upstream version bump. I'll merge shortly.

Update tools-deps variants to 1.11.1.1182

---

src/docker_clojure/config.clj
src/docker_clojure/core.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Fairly standard version bump except for the race condition fix in 7d87d0369da1077df2d7a31a92b1e9f0beda0232. I'll merge shortly, but let me know if you have any thoughts, @Quantisan.

Update tools-deps variants to 1.11.1.1189

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Normal version bump. I'll merge shortly.

Update tools-deps variants to 1.11.1.1200

---

src/docker_clojure/config.clj
target/debian-bullseye-11/lein/Dockerfile
target/debian-bullseye-17/lein/Dockerfile
target/debian-bullseye-19/lein/Dockerfile
target/debian-bullseye-8/lein/Dockerfile
target/debian-bullseye-slim-11/lein/Dockerfile
target/debian-bullseye-slim-17/lein/Dockerfile
target/debian-bullseye-slim-19/lein/Dockerfile
target/debian-bullseye-slim-8/lein/Dockerfile
target/eclipse-temurin-11-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-11-jdk-focal/lein/Dockerfile
target/eclipse-temurin-11-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-17-jdk-focal/lein/Dockerfile
target/eclipse-temurin-17-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-19-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-19-jdk-focal/lein/Dockerfile
target/eclipse-temurin-19-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-8-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-8-jdk-focal/lein/Dockerfile
target/eclipse-temurin-8-jdk-jammy/lein/Dockerfile

Standard upstream release. I'll merge shortly.

Update leiningen to 2.10.0

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile

Normal upstream version bump. Will merge shortly.

Update tools-deps variants to 1.11.1.1208

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1124

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1237

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1252

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-19/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-19/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-19-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Standard upstream release bump

Update tools.deps to 1.11.1.1267

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Here goes the first test of automated official-images pull requests!

Update tools-deps variants to 1.11.1.1273

---

src/docker_clojure/config.clj
src/docker_clojure/core.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1323

---

src/docker_clojure/dockerfile/lein.clj
target/debian-bullseye-11/lein/Dockerfile
target/debian-bullseye-17/lein/Dockerfile
target/debian-bullseye-20/lein/Dockerfile
target/debian-bullseye-8/lein/Dockerfile
target/debian-bullseye-slim-11/lein/Dockerfile
target/debian-bullseye-slim-17/lein/Dockerfile
target/debian-bullseye-slim-20/lein/Dockerfile
target/debian-bullseye-slim-8/lein/Dockerfile
target/eclipse-temurin-11-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-11-jdk-focal/lein/Dockerfile
target/eclipse-temurin-11-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-17-jdk-focal/lein/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-20-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-20-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-8-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-8-jdk-focal/lein/Dockerfile
target/eclipse-temurin-8-jdk-jammy/lein/Dockerfile

Not sure why this broke but @technomancy suggested trying this and it seems to have fixed it. Will merge shortly.

Fix lein gpg keyserver

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps to 1.11.1.1347

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps to 1.11.1.1405

---

src/docker_clojure/config.clj
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-20/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-20/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-20-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Update tools-deps variants to 1.11.1.1413

---

src/docker_clojure/dockerfile.clj
src/docker_clojure/dockerfile/boot.clj
src/docker_clojure/dockerfile/lein.clj
src/docker_clojure/dockerfile/tools_deps.clj
test/docker_clojure/core_test.clj
test/docker_clojure/dockerfile_test.clj
test/docker_clojure/manifest_test.clj
test/docker_clojure/test_runner.clj

I ran clj-kondo on the codebase and these were the warnings it flagged. Thinking about adding it and cljfmt to a git commit hook and CI pipeline soon...

Fix clj-kondo warnings

---

src/docker_clojure/config.clj
target/debian-bookworm-11/tools-deps/Dockerfile
target/debian-bookworm-17/tools-deps/Dockerfile
target/debian-bookworm-21/latest/Dockerfile
target/debian-bookworm-21/tools-deps/Dockerfile
target/debian-bookworm-8/tools-deps/Dockerfile
target/debian-bookworm-slim-11/tools-deps/Dockerfile
target/debian-bookworm-slim-17/tools-deps/Dockerfile
target/debian-bookworm-slim-21/tools-deps/Dockerfile
target/debian-bookworm-slim-8/tools-deps/Dockerfile
target/debian-bullseye-11/tools-deps/Dockerfile
target/debian-bullseye-17/tools-deps/Dockerfile
target/debian-bullseye-21/tools-deps/Dockerfile
target/debian-bullseye-8/tools-deps/Dockerfile
target/debian-bullseye-slim-11/tools-deps/Dockerfile
target/debian-bullseye-slim-17/tools-deps/Dockerfile
target/debian-bullseye-slim-21/tools-deps/Dockerfile
target/debian-bullseye-slim-8/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-11-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-21-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-21-jdk-jammy/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-focal/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-jammy/tools-deps/Dockerfile

Routine upstream version bump. Will merge when CI is green.

Update tools-deps variants to 1.11.1.1435

---

src/docker_clojure/config.clj
target/debian-bookworm-11/lein/Dockerfile
target/debian-bookworm-17/lein/Dockerfile
target/debian-bookworm-21/latest/Dockerfile
target/debian-bookworm-21/lein/Dockerfile
target/debian-bookworm-8/lein/Dockerfile
target/debian-bookworm-slim-11/lein/Dockerfile
target/debian-bookworm-slim-17/lein/Dockerfile
target/debian-bookworm-slim-21/lein/Dockerfile
target/debian-bookworm-slim-8/lein/Dockerfile
target/debian-bullseye-11/lein/Dockerfile
target/debian-bullseye-17/lein/Dockerfile
target/debian-bullseye-21/lein/Dockerfile
target/debian-bullseye-8/lein/Dockerfile
target/debian-bullseye-slim-11/lein/Dockerfile
target/debian-bullseye-slim-17/lein/Dockerfile
target/debian-bullseye-slim-21/lein/Dockerfile
target/debian-bullseye-slim-8/lein/Dockerfile
target/eclipse-temurin-11-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-11-jdk-focal/lein/Dockerfile
target/eclipse-temurin-11-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-17-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-17-jdk-focal/lein/Dockerfile
target/eclipse-temurin-17-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-21-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-21-jdk-jammy/lein/Dockerfile
target/eclipse-temurin-8-jdk-alpine/lein/Dockerfile
target/eclipse-temurin-8-jdk-focal/lein/Dockerfile
target/eclipse-temurin-8-jdk-jammy/lein/Dockerfile

Quick follow-on bug fix release of lein. Will merge shortly.

Update lein variants to 2.11.1

---

.github/workflows/ci.yml
.github/workflows/official-images-pr.yml
bb.edn
deps.edn
src/docker_clojure/core.clj

Hadn't done this in awhile and was getting some deprecation warnings from GitHub Actions

Update deps and actions

---

.github/workflows/ci.yml

Not sure why antq didn't see these in #227 🤷🏻

Update some straggler GH action versions

---

src/docker_clojure/dockerfile/tools_deps.clj
target/eclipse-temurin-11-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-17-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-21-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-24-jdk-alpine/tools-deps/Dockerfile
target/eclipse-temurin-8-jdk-alpine/tools-deps/Dockerfile

Install rlwrap in alpine variants

---

.github/workflows/ci.yml
.github/workflows/official-images-pr.yml
deps.edn

Update deps and build tool versions
